### PR TITLE
Update to use OrdHashMap

### PR DESCRIPTION
**Pull request by phadej**
WIP

### CODE REVIEW

**Comment by fizruk** [comment]
@phadej can I close this?

**Comment by fizruk** [comment]
This awaits the release of `swagger2`.

**Comment by phadej** [comment]
It's based on my ghc-8.0 pull request, `stack.yaml`s use the current master of `swagger2` with `InsOrdHashMap`. Obviously it will require lower bound to be bumped

**Comment by fizruk** [comment]
LGTM 👍

**Comment by phadej** [comment]
Imported doctest magic from ekmett's packages, seems to work better in some corner cases

**Pull request merged**
