### PR TITLE
Fix to make it work with the current unerleased servant 0.5 version

### PR DESCRIPTION
**Pull request by yogsototh**
As it doesn't work with the actually released servant 0.4 version you might prefer to merge it in another branch until servant 0.5 is released.

Best!

### CODE REVIEW

**Comment by dmjio** [comment]
@yogsototh this should work with the current `servant-0.4`. @fizruk can you confirm?

**Comment by fizruk** [comment]
@yogsototh it should work with `servant-0.4.4.5` (at least it does for me).
Can you tell us more about what is not working for you?

**Comment by yogsototh** [comment]
I only changed the code of example to make it work with swagger 0.5 (which is still on github only).

For example I changed EitherT to ExceptT.

This pull request is here to help when swagger will upgrade to 0.5.

I don't believe you should merge it in master for now.
I tried to compile it with swagger-0.4.4.5 and it didn't compile. The compiler complain about the use of ExceptT instead of EitherT.

**Comment by fizruk** [comment]
@yogsototh I see your changes bring `example` project up to date with servant's HEAD, yes.
We are indeed not going to merge these changes until `servant-0.5` is out.

> I tried to compile it with swagger-0.4.4.5 and it didn't compile.

How did you try to compile it? `stack build example`? `cd example/ && cabal install`?

**Comment by yogsototh** [comment]
First I removed the dependencies to my local servant in my `stack.yml`:

~~~
git diff                                                                                                                         ⏎ master ✱
diff --git a/stack.yaml b/stack.yaml
index 0abc7ca..e1c029e 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -7,17 +7,17 @@ resolver: lts-3.11
 packages:
 - '.'
 - example/
-- '../servant/servant/'
-- '../servant/servant-blaze/'
-- '../servant/servant-cassava/'
-- '../servant/servant-client/'
-- '../servant/servant-docs/'
-- '../servant/servant-examples/'
-- '../servant/servant-foreign/'
-- '../servant/servant-js/'
-- '../servant/servant-lucid/'
-- '../servant/servant-mock/'
-- '../servant/servant-server/'
+# - '../servant/servant/'
+# - '../servant/servant-blaze/'
+# - '../servant/servant-cassava/'
+# - '../servant/servant-client/'
+# - '../servant/servant-docs/'
+# - '../servant/servant-examples/'
+# - '../servant/servant-foreign/'
+# - '../servant/servant-js/'
+# - '../servant/servant-lucid/'
+# - '../servant/servant-mock/'
+# - '../servant/servant-server/'

 # Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
 extra-deps:
~~~

And then in the root I simply did a `stack build`:

~~~
stack build                                                                                                                        master ✱
example-0.1.0.0: configure
example-0.1.0.0: build

--  While building package example-0.1.0.0 using:
      /Users/esposito/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0 build exe:swagger-file exe:swagger-server --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/esposito/dev/y/servant-swagger/.stack-work/logs/example-0.1.0.0.log

    Configuring example-0.1.0.0...
    Preprocessing executable 'swagger-file' for example-0.1.0.0...
    Preprocessing executable 'swagger-server' for example-0.1.0.0...
    [1 of 1] Compiling Main             ( Server.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/swagger-server/swagger-server-tmp/Main.o ) [Servant.Swagger changed]

    Server.hs:58:41:
        Couldn't match type ‘Control.Monad.Trans.Either.EitherT
                               ServantErr IO Swagger’
                       with ‘ExceptT ServantErr IO Swagger’
        Expected type: Server API
          Actual type: ExceptT ServantErr IO Swagger
                       :<|> ((TodoId
                              -> Control.Monad.Trans.Either.EitherT ServantErr IO Todo)
                             :<|> ((TodoId
                                    -> Todo
                                    -> Control.Monad.Trans.Either.EitherT ServantErr IO (Maybe Todo))
                                   :<|> (Control.Monad.Trans.Either.EitherT ServantErr IO Todo
                                         :<|> (Todo
                                               -> Control.Monad.Trans.Either.EitherT
                                                    ServantErr IO Todo))))
        In the second argument of ‘serve’, namely ‘endpoints’
        In the second argument of ‘($)’, namely
          ‘serve (Proxy :: Proxy API) endpoints’
~~~

**Comment by dmjio** [comment]
@yogsototh, It seems like stack is still looking for `servant-0.5` (Since it's expecting ExceptT over EitherT). We should probably put an upper bound on servant (and just version the deps. in general) inside `servant-swagger` cc @fizruk.

**Comment by fizruk** [comment]
@yogsototh the error indicates that your local `servant` is using `ExceptT`, so I guess you have HEAD rather than `servant-0.4.*`.

You can simply remove local `servant` packages from `stack.yaml` to build against `servant` from Stackage snapshot.

@dmjio The upper bound might make sense for the `example/` project. For `servant-swagger` itself I am not so sure, since it should work for HEAD too (as you can see from this PR, only example's code is changed).

**Comment by dmjio** [comment]
Might be good to keep this open for when `servant-0.5` is released.

**Pull request merged**
