### PR TITLE
Fix: validation on NoContent

### LINKED ISSUE #58: ToJSON instance for NoContent
This relates to #47. When defining a JSON API containing `NoContent`, e.g:
```Haskell
type DeleteAPI = "widget" :> Capture "id" String :> DeleteNoContent '[JSON] NoContent
```
it's not possible to run `validateEveryToJSON` on it. This fails with:
```Haskell
No instance for (ToJSON NoContent)
  arising from a use of ‘validateEveryToJSON’
```
How should this be handled?

### LINKED ISSUE #96: Exclude NoContent from types tested by 'validateEveryToJSON'
Currently we have:

```haskell
validateEveryToJSON 
    :: forall proxy api. TMap (Every [Typeable, Show, Arbitrary, ToJSON, ToSchema]) 
                              (BodyTypes JSON api) 
    => proxy api
    -> Spec
```

If the API has stuff like `Delete JSON '[NoContent]` in it, you end up having to write a bogus `instance ToJSON NoContent` in order to please `validateEveryToJSON`.

Let's replace `BodyTypes JSON api` with `Remove NoContent (BodyTypes JSON api)`.

### PR DESCRIPTION
**Pull request by fisx**
Fixes #96

Fixes #58

### CODE REVIEW

**Comment by fisx** [comment]
sorry about the whitespace edits, feel free to cherry-pick!  :)

**Comment by fisx** [comment]
any comments on this?  it should be relatively non-controversial...

**Comment by fisx** [comment]
ping...

**Comment by fizruk** [comment]
@fisx all looks great! Thanks and sorry for the long wait!

**Pull request merged**
