### PR TITLE
Restore support for servant 0.4

### PR DESCRIPTION
**Pull request by fizruk**

### CODE REVIEW

**Comment by fizruk** [comment]
I am getting this error for GHC 7.8 build:

```
servant-swagger-1.0.3: test (suite: doctest)
/home/travis/build/haskell-servant/servant-swagger/src/Servant/Swagger/Internal.hs:83:0:
     error: missing binary operator before token "("
/home/travis/build/haskell-servant/servant-swagger/src/Servant/Swagger/Internal.hs:180:0:
     error: missing binary operator before token "("
doctest: doctest: phase `C pre-processor' failed (exitcode = 1)
```

The problem seems to be that `MIN_VERSION_servant` is not in scope (so it get's replaced by nothing causing this weird error message). I am not sure though why it is not is scope and how to fix it.

**Comment by jkarni** [comment]
Pushed a commit that hopefully fixes it.

**Comment by jkarni** [comment]
Hm, apparently not. 

https://github.com/ekmett/linear/commit/d0cd4fee271d72029bb385674409ee1237f4c17d has a solution, but is a bit involved.

**Comment by fizruk** [comment]
@jkarni are you willing to incorporate that solution? Seems mostly copy-paste.

**Comment by fizruk** [comment]
The required change seems to be done in 16d428ee320b1afba5146da3e30276d2da760d09, so here we need a rebase.

**Comment by phadej** [comment]
I didn't noticed I fixed something else as well :P

**Comment by fizruk** [comment]
I guess I overestimated the need to support `servant-0.4`.
Please reopen this PR if you need `servant-0.4` support.

**Pull request closed without merging**
